-- Additive migration for Ride Service.
-- Keeps existing tables/columns used by admin and driver-location services.

BEGIN;

CREATE TABLE IF NOT EXISTS roles (
    value TEXT NOT NULL PRIMARY KEY
);
INSERT INTO roles (value) VALUES ('PASSENGER'), ('DRIVER'), ('ADMIN')
ON CONFLICT (value) DO NOTHING;

CREATE TABLE IF NOT EXISTS user_status (
    value TEXT NOT NULL PRIMARY KEY
);
INSERT INTO user_status (value) VALUES ('ACTIVE'), ('INACTIVE'), ('BANNED')
ON CONFLICT (value) DO NOTHING;

CREATE TABLE IF NOT EXISTS ride_status (
    value TEXT NOT NULL PRIMARY KEY
);
INSERT INTO ride_status (value) VALUES
    ('REQUESTED'), ('MATCHED'), ('EN_ROUTE'), ('ARRIVED'),
    ('IN_PROGRESS'), ('COMPLETED'), ('CANCELLED')
ON CONFLICT (value) DO NOTHING;

CREATE TABLE IF NOT EXISTS vehicle_type (
    value TEXT NOT NULL PRIMARY KEY
);
INSERT INTO vehicle_type (value) VALUES ('ECONOMY'), ('PREMIUM'), ('XL')
ON CONFLICT (value) DO NOTHING;

CREATE TABLE IF NOT EXISTS ride_event_type (
    value TEXT NOT NULL PRIMARY KEY
);
INSERT INTO ride_event_type (value) VALUES
    ('RIDE_REQUESTED'), ('DRIVER_MATCHED'), ('DRIVER_ARRIVED'),
    ('RIDE_STARTED'), ('RIDE_COMPLETED'), ('RIDE_CANCELLED'),
    ('STATUS_CHANGED'), ('LOCATION_UPDATED'), ('FARE_ADJUSTED')
ON CONFLICT (value) DO NOTHING;

ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ACTIVE';
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS attrs JSONB DEFAULT '{}'::jsonb;

ALTER TABLE coordinates ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE coordinates ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE coordinates ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';

ALTER TABLE rides ADD COLUMN IF NOT EXISTS ride_number VARCHAR(50);
ALTER TABLE rides ADD COLUMN IF NOT EXISTS vehicle_type TEXT;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS estimated_fare DECIMAL(10, 2);
ALTER TABLE rides ADD COLUMN IF NOT EXISTS final_fare DECIMAL(10, 2);
ALTER TABLE rides ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 1;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS requested_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE rides ADD COLUMN IF NOT EXISTS matched_at TIMESTAMPTZ;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS arrived_at TIMESTAMPTZ;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS cancellation_reason TEXT;
ALTER TABLE rides ADD COLUMN IF NOT EXISTS pickup_coordinate_id INTEGER REFERENCES coordinates(id);
ALTER TABLE rides ADD COLUMN IF NOT EXISTS destination_coordinate_id INTEGER REFERENCES coordinates(id);
ALTER TABLE rides ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS idx_rides_ride_number ON rides(ride_number)
    WHERE ride_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS ride_events (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ride_id VARCHAR(50) NOT NULL REFERENCES rides(id),
    event_type TEXT REFERENCES ride_event_type(value),
    event_data JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_ride_events_ride_id ON ride_events(ride_id);

COMMIT;
